AWSTemplateFormatVersion: 2010-09-09
Description: 'Security services stack for C3 project'

Resources:
  # AWS Config
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: 'C3-ConfigRecorder'
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResources: true
      RoleARN: !GetAtt ConfigRole.Arn

  ConfigRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWS_ConfigRole

  # Inspector
  InspectorAssessmentTarget:
    Type: AWS::Inspector::AssessmentTarget
    Properties:
      AssessmentTargetName: 'Web-Services-Target'
      ResourceGroupArn: !GetAtt InspectorResourceGroup.Arn

  InspectorResourceGroup:
    Type: AWS::Inspector::ResourceGroup
    Properties:
      ResourceGroupTags:
        - Key: Name
          Value: 'Web Services Instance - C3'

  InspectorAssessmentTemplate:
    Type: AWS::Inspector::AssessmentTemplate
    Properties:
      AssessmentTargetArn: !Ref InspectorAssessmentTarget
      AssessmentTemplateName: 'C3-SecurityAssessment'
      DurationInSeconds: 900
      RulesPackageArns:
        - arn:aws:inspector:us-east-1:316112463485:rulespackage/0-gEjTy7T7
        - arn:aws:inspector:us-east-1:316112463485:rulespackage/0-rExsr2X8

Outputs:
  ConfigRecorderName:
    Description: 'Name of the AWS Config Recorder'
    Value: !Ref ConfigRecorder

  InspectorAssessmentTemplateName:
    Description: 'Name of the Inspector Assessment Template'
    Value: !Ref InspectorAssessmentTemplate
