Resources:
  InspectorAssessmentTarget:
    Type: AWS::Inspector::AssessmentTarget
    Properties:
      AssessmentTargetName: Assessment Target - All Instances
      ResourceGroupArn: !GetAtt InspectorResourceGroup.Arn

  InspectorResourceGroup:
    Type: AWS::Inspector::ResourceGroup
    Properties:
      ResourceGroupTags:
        - Key: Name
          Value: Web Service Instance - C3X

  InspectorAssessmentTemplate:
    Type: AWS::Inspector::AssessmentTemplate
    Properties:
      AssessmentTargetArn: !Ref InspectorAssessmentTarget
      AssessmentTemplateName: Assessment Template - Default
      DurationInSeconds: 900
      RulesPackageArns: 
        - arn:aws:inspector:us-east-1:316112463485:rulespackage/0-gEjTy7T7  # Network Reachability
        - arn:aws:inspector:us-east-1:316112463485:rulespackage/0-rExsr2X8  # Security Best Practices
      UserAttributesForFindings:
        - Key: NetworkAssessment
          Value: Enabled
        - Key: HostAssessment
          Value: Enabled

Outputs:
  AssessmentTargetArn:
    Description: ARN of the Inspector Assessment Target
    Value: !Ref InspectorAssessmentTarget
  
  AssessmentTemplateArn:
    Description: ARN of the Inspector Assessment Template
    Value: !Ref InspectorAssessmentTemplate   